### ISSUE TITLE
[REQ] Support Jakarta EE 9

### ISSUE THREAD

**Issue by ferblaca** [steinarb/mockrunner#8]
With the upgrade to Spring Boot 3 and the adoption of Jakarta EE9, Jakarta EE 9 a new top-level jakarta package, replacing EE 8’s javax top-level package.

For example, the current `com.mockrunner.mock.jms.MockSession` class is using the `javax.jms` packages instead of `jakarta.jms`.

Is there provision for a release using Jakarta EE9?

**Comment by ferblaca** [comment]
@steinarb  Is this repository maintained? If such a contribution is made, would it at least be included?

**Comment by steinarb** [comment]
@ferblaca This is the original repo that was converted from sourceforge CVS, but it is no longer where the project lives.

The project currently lives at https://github.com/mockrunner/mockrunner
